---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: esphome-secrets
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: esphome-secrets
    creationPolicy: Owner
    template:
      data:
        secrets.yaml: |-
          api_key: "{{ .esphome_api_key }}"
          domain: "internal"
          mqtt_host: "mqtt.${DOMAIN}"
          mqtt_pwd: "{{ .esphome_mqtt_password }}"
          mqtt_user: "{{ .esphome_mqtt_username }}"
          ota_password: "{{ .esphome_ota_password }}"
          timezone: "${TIMEZONE}"
          wifi_fallback_ssid_password: "{{ .esphome_fallback_wifi_password }}"
          wifi_password: "{{ .wifi_password }}"
          wifi_ssid: "{{ .wifi_ssid }}"
  dataFrom:
    - extract:
        key: ESP Home
      rewrite:
        - regexp:
            source: "[^a-zA-Z0-9-]"
            target: "_"
        - regexp:
            source: "(.*)"
            target: "esphome_$1"
    - extract:
        key: ITO (WIFI)
      rewrite:
        - regexp:
            source: "(.*)"
            target: "wifi_$1"
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: esphome-deploykey
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: esphome-deploykey
    creationPolicy: Owner
  data:
    - secretKey: id_ed25519
      remoteRef:
        key: ESP Home
        property: gh deploy key
