# Socket address to listen on
listen = "[::]:8080"
allowed-hosts = []
api-endpoint = "https://attic.nebular-grid.space/"

# Database connection
[database]
url = "sqlite:///var/lib/atticd/server.db?mode=rwc"

# File storage configuration
[storage]
type = "local"
path = "/var/lib/atticd/storage"

# Data chunking
[chunking]
nar-size-threshold = 65536 # chunk files that are 64 KiB or larger
min-size = 16384            # 16 KiB
avg-size = 65536            # 64 KiB
max-size = 262144           # 256 KiB

# Compression
[compression]
type = "zstd"

# Garbage collection
[garbage-collection]
interval = "12 hours"
