listen = "[::]:8080"
api-endpoint = "https://attic.nebular-grid.space"

[database]
url = "sqlite:///attic/storage/server.db?mode=rwc"

[storage]
type = "local"
path = "/attic/storage"

[chunking]
nar-size-threshold = 65536
min-size = 16384
avg-size = 65536
max-size = 262144

[garbage-collection]
interval = "12 hours"
