---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "nebular-grid.space"
spec:
  secretName: "nebular-grid.space-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "nebular-grid.space"
  dnsNames:
    - "nebular-grid.space"
    - "*.nebular-grid.space"
